### ISSUE TITLE
Actor>Vehicle - Error thrown on vehicle actors that only have Check activity configured.

### ISSUE THREAD

**Issue by secondworldpublishing** [koboldpress/black-flag#869]
When a feature item has only a check activity configured within a Vehicle Actor, which you click on the heading in the actor, nothing happens.  An error is also thrown in the JS console:

validation.mjs:19 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at isValidUnit (validation.mjs:19:12)
    at _prepareFormattingOptions (number.mjs:86:23)
    at numberFormat (number.mjs:115:37)
    at Object.get (duration-field.mjs:51:13)
    at get chatTags (activity.mjs:159:38)
    at CheckActivity._activationChatContext (activity.mjs:974:26)
    at CheckActivity.createActivationMessage (activity.mjs:1040:30)
    at CheckActivity.activate (activity.mjs:546:36)

![Screenshot 2024-12-07 at 9 46 04 AM](https://github.com/user-attachments/assets/42dd8f2a-ae13-4bc6-a1e5-760aa8b4425b)

[fvtt-Actor-carriage-TruIRFIrvzdRVsuJ.json](https://github.com/user-attachments/files/18049344/fvtt-Actor-carriage-TruIRFIrvzdRVsuJ.json)

**Comment by arbron** [comment]
Make sure you are on the final version of `1.1.055`, not the pre-release version I made for you. This should be fixed in that version.

**Comment by secondworldpublishing** [comment]
I had the final version of 1.1.055 installed before submitting this ticket.  The errors also occurred in the pre-release.
